repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v6.0.0
        hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    -   repo: https://github.com/python-jsonschema/check-jsonschema
        rev: 0.37.0
        hooks:
            -   id: check-github-workflows
                args: [ "--verbose" ]
    -   repo: https://github.com/tox-dev/tox-ini-fmt
        rev: "1.7.1"
        hooks:
            -   id: tox-ini-fmt
                args: [ "-p", "lint" ]
    -   repo: https://github.com/tox-dev/pyproject-fmt
        rev: "v2.20.0"
        hooks:
            -   id: pyproject-fmt
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.7
      hooks:
          - id: ruff
          - id: ruff-format
            args:
                - --check
                - --config
                - ruff.toml
    -   repo: https://github.com/adamchainz/djade-pre-commit
        rev: "1.9.0"
        hooks:
            -   id: djade
                args: [ --target-version, "5.2" ]  # Replace with Django version
    -   repo: meta
        hooks:
            -   id: check-hooks-apply
            -   id: check-useless-excludes
