[tox]
requires =
    tox>=4.2
    tox-gh-actions
    tox-uv>=1.20.2
env_list =
    lint
    d{60, 52}-py314-{pg, mysql}
    d{60, 52, 42}-py313-{pg, mysql}
    pkg_meta
skip_missing_interpreters = true

[testenv]
deps =
    pypy-pg: psycopg2cffi
    d42: django==4.2.*
    d42: django-reversion==4.*
    d52: django==5.2.*
    d52: django-reversion==5.*
    d60: django<6.1,>=6.0a1
    d60: django-reversion==5.*
    mysql: mysqlclient
pass_env =
    PGHOST
    PGPORT
    PYTHONDONTWRITEBYTECODE
set_env =
    DBNAME = concurrency
    PYTHONPATH =
    PYTHONPATH = ./src/:tests/demoapp
    mysql: DBENGINE = mysql
    pg: DBENGINE = pg
    sqlite: DBENGINE = sqlite
change_dir = {toxinidir}
commands =
    {posargs:pytest tests -rw --create-db}
dependency_groups = dev
whitelist_externals =
    mkdir
    /usr/local/bin/psql
    /bin/sh
    /usr/local/bin/mysql
    /usr/local/mysql/bin/mysql
    /usr/bin/psql

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --no-config {env_tmp_dir}

[testenv:mysql]
commands =
    - mysql -u root -h 127.0.0.1 -e 'DROP DATABASE IF EXISTS concurrency;'
    - mysql -u root -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS concurrency;'
    {[testenv]commands}

[testenv:pg]
commands =
    - psql  -h $PGHOST -p $PGPORT -c 'DROP DATABASE "concurrency";' -U postgres
    - psql  -h $PGHOST -p $PGPORT  -c 'CREATE DATABASE "concurrency";' -U postgres
    {[testenv]commands}

[testenv:clean]
commands =
    mysql: - mysql -u root -e 'DROP DATABASE IF EXISTS concurrency;'
    pg: - psql -c 'DROP DATABASE "concurrency";' -U postgres

[testenv:docs]
skip_install = false
commands =
    mkdocs build -d ./~build/docs
dependency_groups = docs, type-check, dj

[testenv:type]
description = run type check on code base
commands =
    mypy --strict src/
dependency_groups = type-check, dev
