# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 15:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionalversionmodelselfrelation',
            name='relations',
        ),
        migrations.AddField(
            model_name='conditionalversionmodelselfrelation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.ConditionalVersionModelSelfRelation'),
        ),
    ]
