name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash
    outputs:
      run_tests: ${{ steps.changes.outputs.run_tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: changes
        name: Check for file changes
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        with:
          base: ${{ github.ref }}
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  test:
    needs: [ changes ]
    if: needs.changes.outputs.run_tests == 'true'

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.13" ]
        django: [ "60", "52", "42", "32" ]
        db-engine: [ "pg", "mysql" ]
    env:
      PY_VER: ${{ matrix.python}}
      DJ_VER: ${{ matrix.django}}
      DBENGINE: ${{ matrix.db-engine}}
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: concurrency
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE concurrency;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

      -   name: Install the latest version of uv
          uses: astral-sh/setup-uv@v5
          with:
              version: "latest"
              enable-cache: true
              cache-dependency-glob: |
                  pyproject.toml
                  uv.lock
              cache-suffix: ${{ matrix.python }}-${{ matrix.django }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              python-version: ${{ matrix.python }}

      -   name: Install tox
          run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv --with tox-gh-actions

      -   name: Install Python
          if: matrix.python != '3.13'
          run: uv python install --python-preference only-managed ${{ matrix.python }}

      -   name: Setup test suite
          run: tox run -vv --notest --skip-missing-interpreters false

      - name: Test with
        run: tox run -e d${DJ_VER//.}-py${PY_VER//.}-${DBENGINE}

      -   name: Upload test results to Codecov
          uses: codecov/test-results-action@v1
          with:
              env_vars: OS
              flags: ${{ matrix.django }} ${{ matrix.python }}
              token: ${{ secrets.CODECOV_TOKEN }}
              verbose: true

      -   name: Upload coverage to Codecov
          uses: codecov/codecov-action@v5
          with:
              env_vars: OS,PYTHON
              fail_ci_if_error: true
              files: ./coverage1.xml,./coverage2.xml,!./cache
              flags: unittests
              name: codecov-umbrella
              token: ${{ secrets.CODECOV_TOKEN }}
              verbose: true
